### ISSUE TITLE
短信开发的坑！

### ISSUE THREAD

**Issue by jinzhq** [qcloudsms/qcloudsms#1]
腾讯，让我怎么说你好呢，一个大公司，代码真垃圾！短信单发都不支持了，为啥还在里面？模版消息为啥不弄个demo，让我们自己摸索，你就是这样一个大公司吗？让人失望！而且，论坛问题也没人回答！失望中....
自己的错误如下：1、tel_id 是数字，字符不通过！ 2、参数params，是数组，不是一个完整的字符串，java 里需要用arraylist 加入。完整的串应该是
{    "extend": "",     "sig": "29A3C2D60AF5A368536563C1B867BE64",     "tpl_id": 4352,     "sign": "腾讯云",     "tel": {        "phone": "13604118641",         "nationcode": "86"    },     "type": "0",     "params": [\"1234\", \"4\"]}，
我改造后的demo 代码如下：

package com.combrain.sms.gateway;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.HttpURLConnection;
import java.net.URL;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;
import java.util.List;
import java.util.Random;

import org.json.JSONObject;
 
 
public class TencentSmsSender {
    Random random = new Random();
    int sdkappid;
    String appkey;
    // 请根据我们的说明文档适时调整 url
    final String url = "https://yun.tim.qq.com/v3/tlssmssvr/sendsms";
    
    
    public TencentSmsSender(int sdkappid, String appkey) {
        this.sdkappid = sdkappid;
        this.appkey = appkey;
    }
    
    
    
  
     
//        "sign": "腾讯云", //短信签名，如果使用默认签名，则可以缺省此字段
   
    public void sendMsg(String nationCode, String phoneNumber, String content) {
        long rnd = random.nextInt(999999)%(999999-100000+1)+100000;
        String wholeUrl = String.format("%s?sdkappid=%d&random=%d", url, sdkappid, rnd);        
        try {
            URL object = new URL(wholeUrl);
            HttpURLConnection con = (HttpURLConnection) object.openConnection();
            con.setDoOutput(true);
            con.setDoInput(true);
            con.setRequestProperty("Content-Type", "application/json");
            con.setRequestProperty("Accept", "application/json");
            con.setRequestMethod("POST");
            JSONObject data = new JSONObject();
            JSONObject tel = new JSONObject();
            tel.put("nationcode", nationCode);
            String phone = phoneNumber;
            tel.put("phone", phone);
            data.put("type", "0");
         
            data.put("tpl_id", 4352);
            List<String> places = Arrays.asList("1234", "4");
            data.put("params", places);
            		
            String sig = stringMD5(appkey.concat(phone));
            data.put("sig", sig);
            data.put("tel", tel);
            data.put("sign", "康博软件");
            data.put("extend", "");
            data.put("ext", "");
          
            OutputStreamWriter wr = new OutputStreamWriter(con.getOutputStream(), "utf-8");
            wr.write(data.toString());
            wr.flush();

            // 显示 POST 请求返回的内容
            StringBuilder sb = new StringBuilder();
            int HttpResult = con.getResponseCode();
            if (HttpResult == HttpURLConnection.HTTP_OK) {
                BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream(), "utf-8"));
                String line = null;
                while ((line = br.readLine()) != null) {
                    sb.append(line + "\n");
                }
                br.close();
                System.out.println("" + sb.toString());
            } else {
                System.out.println(con.getResponseMessage());
            }
        } catch (Exception e) {
            e.printStackTrace();
        } 
     

}

    private static String stringMD5(String input) throws NoSuchAlgorithmException {
        MessageDigest messageDigest = MessageDigest.getInstance("MD5");
        byte[] inputByteArray = input.getBytes();
        messageDigest.update(inputByteArray);
        byte[] resultByteArray = messageDigest.digest();
        return byteArrayToHex(resultByteArray);
    }

    private static String byteArrayToHex(byte[] byteArray) {
        char[] hexDigits = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F'};
        char[] resultCharArray = new char[byteArray.length * 2];
        int index = 0;
        for (byte b : byteArray) {
            resultCharArray[index++] = hexDigits[b >>> 4 & 0xf];
            resultCharArray[index++] = hexDigits[b & 0xf];
        }
        return new String(resultCharArray);
    }
}

**Comment by lovemyliwu** [comment]
额，你说的问题官方文档里写得很清楚啊？

https://www.qcloud.com/doc/product/382/5976

**Comment by qcloudsms** [comment]
欢迎pull request, 官方文档中有详细的说明https://www.qcloud.com/document/product/382，如还有疑问，可联系腾讯云短信技术支持3012203387协助
