### ISSUE TITLE
Java的SDK几处错误和不合理的地方

### ISSUE THREAD

**Issue by MiniKnife** [qcloudsms/qcloudsms#11]
1.SmsStatusPullCallbackResult、SmsStatusPullReplyResult中某些定义没有考虑对外可见性，这些明显是JavaBean的类定义也没有按照JavaBean规范定义，字段都是没有修饰符的，没有get/set，造成的结果是demo能跑，我们没法用，因为里面的字段在我们的包空间中不可见
2.代码中有多处System.out.println这样的控制台调试输出，既然项目依赖了common-logging，为什么不用日志框架输出需要的调试信息呢？
3.现在一般公司的Java项目不用maven这类构建工具的太少了，这个项目居然没有用ant也没有用maven，不可理解，给用户使用徒增麻烦
4.HttpURLConnection连接对象没有被安全的关闭和释放
5.类似SmsSingleSender#sendWithParam这样的方法中，居然只能接受ArrayList类型而不是List。。。
6.多处IO操作没有处理IO异常而是直接抛出
7.代码整洁度太差，没有合理的格式化也没有合理的代码
太多了，没精力再挑了。。。。。
综上，这个SDK让我对企鹅云很失望，这个SDK是刚毕业的实习生匆匆忙忙赶工出来的么？这个是对外给客户用的SDK，麻烦找一个稍微有点经验的码农认真对待，谢谢！
（PS：那个bin目录里的jar包，我解压出来看到.project和.classpath一脸懵逼，这是在eclipse里面用File-export-java-jar导出来的？？？！！！）

**Comment by libran7** [comment]
确实，感觉这个demo太敷衍了。楼主有重构的版本么？可以放到github上面么？

**Comment by qcloudsms** [comment]
非常感谢您的建议，为方便客户使用我们提供了maven版本，请移步https://github.com/qcloudsms/qcloudsms_java

**Comment by MiniKnife** [comment]
@libran7 我刚上传到我的项目里了，如果还用得上的话，你可以去看看  :)
