### ISSUE TITLE
请把代码写好~

### ISSUE THREAD

**Issue by runhwguo** [qcloudsms/qcloudsms#17]
既然都是官方的Demo了，请认真写代码，把代码写优雅些。
1. 拼接phoneNumber可以用join(',')
2.网络请求可以封装一下方法
3...

**Comment by unliar** [comment]
所以你可以自己动手啊~
我就参考它动手写了个更加好看的npm包。
1. √ 单发短信
2. √ 模板单发短信
3. √ 群发短信
4. √ 模板群发短信
5. √ 语音验证码
6. √ 语音通知


[qcoudsms](https://github.com/unliar/qcloudsms)

**Comment by qcloudsms** [comment]
@runhwguo 您好，非常感谢提供建议，我们现在提供了相应语言的sdk了
