### ISSUE TITLE
你们都把java代码上传到maven,可以把php的代码也上传到composer吗?

### ISSUE THREAD

**Issue by xiaoxintiaoda** [qcloudsms/qcloudsms#18]
麻烦把php的代码也上传到composer吧...

**Comment by qcloudsms** [comment]
好的，非常感谢您的建议，我们后续会添加进行php composer中。

**Comment by uwang** [comment]
👍 像我这种懒人只习惯去 composer 找代码。。。

**Comment by qcloudsms** [comment]
@haobingwang 您好，我们现在提供了php的sdk，地址是： https://github.com/qcloudsms/qcloudsms_php
