### ISSUE TITLE
PHP 的 SDK 因为使用了常量 CURLINFO_RESPONSE_CODE 只支持 PHP 5.5 以上版本

### ISSUE THREAD

**Issue by yilimi001** [qcloudsms/qcloudsms#4]
PHP 的 SDK 因为使用了常量 CURLINFO_RESPONSE_CODE 只支持 PHP 5.5 以上版本
具体可看 http://php.net/manual/en/function.curl-getinfo.php#refsect1-function.curl-getinfo-changelog

换 CURLINFO_HTTP_CODE 这个可以支持更低版本的。

**Comment by yilimi001** [comment]
说的是 https://github.com/qcloudsms/qcloudsms/blob/master/demo/php/SmsSender.php 这个文件里

**Comment by qcloudsms** [comment]
谢谢你的issume，我们会更新，同时欢迎提交PR
